name: Deno cache
runs:
   using: 'composite'
   steps:
      -  name: Set Deno cache dir
         shell: bash
         run: echo "DENO_DIR=$RUNNER_TEMP${{ runner.os == 'Windows' && '\\' || '/'  }}deno_cache" >> $GITHUB_ENV

      -  name: Cache Deno dependencies
         id: cache-deno
         uses: actions/cache@v4.0.2
         with:
            key: ${{ hashFiles('./deno.lock') }}
            path: ${{ env.DENO_DIR }}

      -  name: Restore Deno dependencies
         shell: bash
         run: find scripts/ -regex ".*\.[jt]sx*" -exec deno cache --config=deno.json {} \;
