name: Publish

on:
   push:
      tags:
       - "v*.*.*"

jobs:
   publish:
      name: Publish
      runs-on: ubuntu-latest

      permissions:
         contents: write

      steps:
         -  name: Clone repository
            uses: actions/checkout@v4

         -  name: Install Deno
            uses: denoland/setup-deno@v1
            with:
               deno-version: v1.x

         -  name: Build
            run: |
               set -e
               deno run -A scripts/build.ts modules/*
               OWD="${PWD}"
               mkdir -p dist
               for DIR in modules/*/dist/; do
                  pushd $DIR
                  BASE="$(ls -d * | tail -n 1)"
                  cp "${BASE}/metadata.json" "${OWD}/dist/${BASE}.metadata.json"
                  7z a -bb0 -sdel "${BASE}.zip" $BASE/*
                  rmdir $BASE
                  mv "${BASE}.zip" "${OWD}/dist/"
                  popd
                  rmdir $DIR
               done

         -  name: Release
            id: release
            uses: softprops/action-gh-release@v2
            with:
               files: dist/*

         -  name: Update vault.json
            run: |
               set -e
               for URL in ${{ fromJSON(steps.release.outputs.assets).*.browser_download_url }}; do
                  ARCHIVE="${URL##*/}"
                  IFS="@" read -r ID VERSION <<< "$ARCHIVE"
                  ID="$(tr . / <<< "${ID}")"
                  VERSION="${VERSION%.zip}"
                  VERSION="${VERSION/?}"
                  yq -i ".modules.[\"${ID}\"].v[\"${VERSION}\"].artifacts += [\"${URL}\"]" vault.json
               done

         -  name: Commit changes
            uses: stefanzweifel/git-auto-commit-action@v4
            with:
               commit_message: Update vault.json
