name: Publish

on:
   push:
      tags:
       - "v*.*.*"

jobs:
   publish:
      name: Publish
      runs-on: ubuntu-latest

      permissions:
         contents: write

      steps:
         -  name: Clone repository
            uses: actions/checkout@v4

         -  name: Install Deno
            uses: denoland/setup-deno@v1
            with:
               deno-version: v1.x

         -  name: Build
            run: |
               set -e
               deno run -A scripts/build.ts modules/*
               OWD="${PWD}"
               mkdir -p dist
               for DIR in modules/*/dist/; do
                  pushd $DIR
                  BASE="$(ls -d * | tail -n 1)"
                  cp "${BASE}/metadata.json" "${OWD}/dist/${BASE}.metadata.json"
                  7z a -bb0 -sdel "${BASE}.zip" $BASE/*
                  rm -rf $BASE
                  mv "${BASE}.zip" "${OWD}/dist/"
                  popd
                  rmdir $DIR
               done

         -  name: Release
            uses: softprops/action-gh-release@v2
            with:
               files: dist/*

         -  name: Update vault.json
            run: |
               set -e
               for ZIP in dist/*.zip; do
                  ARCHIVE="${ZIP##*/}"
                  IFS="@" read -r ID VERSION <<< "$ARCHIVE"
                  echo $ID
                  echo $VERSION
                  ID="$(tr . / <<< "${ID}")"
                  echo $ID
                  VERSION="${VERSION%.zip}"
                  echo $VERSION
                  VERSION="${VERSION/?}"
                  echo $VERSION
                  URL="https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/${ARCHIVE}"
                  echo $URL
                  yq -i ".modules[\"${ID}\"].v[\"${VERSION}\"].artifacts += [\"${URL}\"]" vault.json
               done
               rm -rf dist

         -  name: Git commit, rebase onto master
            env:
               PUSH_BRANCH: main
               TMP_BRANCH: ${{ github.repository }}${{ github.run_id}}
            run: |
               git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
               git config --local user.name "$GITHUB_ACTOR"
               git checkout -b $TMP_BRANCH
               git add vault.json
               git commit -m 'Updated vault.json'
               git fetch
               git checkout -b $PUSH_BRANCH --track origin/${PUSH_BRANCH}
               git rebase $TMP_BRANCH $PUSH_BRANCH
               git push
